### ISSUE TITLE
SentTo does not work if the folder is on an E: drive and contains " & " like "A & B"

### ISSUE THREAD

**Issue by DocBrown101** [emoacht/HashPad#26]
Can be reproduced quite easily by simply creating a folder with a name that includes spaces.

In it you place a file that you want to open with the HashPad via "SenTo".

**Comment by emoacht** [comment]
Thanks for reporting.
But I could not reproduce. Could you elaborate exactly how you have tested it?

**Comment by DocBrown101** [comment]
To be able to debug it in Visusal Studio, you can create the launchSettings json and put a file there with spaces.
![image](https://user-images.githubusercontent.com/11892773/202892747-abfe0e2b-2640-4149-a484-134c90398758.png)

Then you only have to set a breakpoint in the MainWindow.xaml file in line 121.
![image](https://user-images.githubusercontent.com/11892773/202892824-bc4f3092-a6f7-42ae-b396-0b42193e6425.png)

The path to the file was split into three parts and therefore the file is no longer found.

**Comment by emoacht** [comment]
I think this issue is about the case where SendTo action triggers the OS to call this app. The arguments in this case depends on how the OS specify those arguments when calling this app.
As far as I have tested, in the case of SendTo, the full path of file is provided in the second argument obtained by `Environment.GetCommandLineArgs` method regardless of whether the path includes spaces.
For example, I can successfully call this app by SendTo from the context menu of `C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe`.
Could you show the actual file example which fails by SendTo?

**Comment by DocBrown101** [comment]
Yes, it probably has something to do with the operating system. If the path had been passed in double quotes, it would be correct and found in the second position in the args.

Due to the spaces in the path, the operating system incorrectly assumes additional parameters.

![image](https://user-images.githubusercontent.com/11892773/202902674-405065b1-29b1-473b-9b6c-da051fccf273.png)

Therefore, I can't think of a solution for it at the moment. The SendTo would have to wrap the path in double quotes.

https://learn.microsoft.com/en-us/dotnet/api/system.environment.getcommandlineargs?view=net-7.0#remarks

**Comment by emoacht** [comment]
What are you intend to show by the screenshot?
I think the point is how the OS automatically provides the argument in the of SendTo. There is nothing this app can do when the OS provides it.
Then, could you give actual file example which fails by SendTo?

**Comment by DocBrown101** [comment]
Yes, that's right, it's something else entirely. I think we can close the bug. It only occurs on the E drive. But there I had all my iso files.

**Comment by emoacht** [comment]
So your E drive has something different from other drives because of mystical reasons.
Okay, I added a function to attempt to restore the full path from fragments. 71073baf99544c86585e64b3d83f5070fa7a6ee1
I don't know whether it would make any difference for your particular case though.
