### ISSUE TITLE
Request for Multilingual Support (Simplified/Traditional Chinese)

### ISSUE THREAD

**Issue by nkh0472** [emoacht/HashPad#4]
And I can help for Chinese translation.

**Comment by emoacht** [comment]
Thank you for your suggestion.
Can you translate English to both Simplified Chinese (zh-cn) and Traditional Chinese (zh-tw)?

**Comment by nkh0472** [comment]
Simplified Chinese is OK for me.
I'm not very familiar with Traditional Chinese.
However, the difference between their words is not very big.
I thought, even if I don't rely on translation software, I can probably handle it.

**Comment by emoacht** [comment]
Okay, Never mind.
In principle, the translation should be done by a person who is familiar with the language and so we can leave the translation to Traditional Chinese to someone who is familied with it.
I am still working on switching function of languages and this time I will do the coding matter.
Could you translate the following English to Simplified Chinese?

- Browse ->
- Compute Hash Value ->
- Expected Value ->
- File Path ->
- Match! ->
- Add to 'Send to' of Explorer's context menu ->
- Compute hash value automatically after file path is filled ->
- Read clipboard automatically before computing hash value ->
- Read Clipboard ->
- Stop ->

**Comment by nkh0472** [comment]
You could make the language file as some kind of text file (like xml, ini or txt) so we can edit it on github easily.

In zh-CN:
```
Browse -> 浏览
Compute Hash Value -> 计算Hash值
Expected Value -> 对比值
File Path -> 文件路径
Match! -> 匹配！
Add to 'Send to' of Explorer's context menu -> 加入右键"发送到…"菜单
Compute hash value automatically after file path is filled -> 填写文件路径后立即开始计算
Read clipboard automatically before computing hash value -> 计算前自动读取剪切板
Read Clipboard -> 读取剪切板
Stop -> 停止
```
In zh-TW:
```
Browse -> 瀏覽
Compute Hash Value -> 計算Hash值
Expected Value -> 期望值
File Path -> 檔案路徑
Match! -> 匹配！
Add to 'Send to' of Explorer's context menu -> 添加到右鍵菜單中的“發送到”
Compute hash value automatically after file path is filled -> 填充檔案路徑後自動開始計算
Read clipboard automatically before computing hash value -> 計算Hash值前自動讀取剪貼板
Read Clipboard -> 閱讀剪貼板
Stop -> 停止計算
```

PS: Since the software has the function of reading the clipboard, you can let the software automatically guess the corresponding algorithm according to the hash length of the clipboard and make a suggestion. It will be very convenient!

**Comment by emoacht** [comment]
Thank you for your work.
I made some modifications and pushed in feature branch. They are in XML format.

- zh-CN https://github.com/emoacht/HashPad/commit/4b97ac38afff0909cbef9b64b5b159bd4ce13d47 [Edited]
- zh-TW https://github.com/emoacht/HashPad/commit/6b60742bbf8e98ed34bce2f9f84ba21ae2fb1619 [Edited]

I put the help wanted label to request any other person to cross-check these languages.

Regarding the function you described in PS, it is already implemented. You should able to see it if it works correctly.

**Comment by emoacht** [comment]
Released.
